#ifndef PRIVATE_H
#define PRIVATE_H
#include <stdbool.h>
#include "rf/clemsacode.h"

extern const uint8_t HOME_1_GARAGE_EXIT_CODE[CLEMSA_CODEGEN_DEFAULT_CODE_SIZE];
extern const uint8_t HOME_1_GARAGE_ENTER_CODE[CLEMSA_CODEGEN_DEFAULT_CODE_SIZE];
extern const uint8_t PARENTS_GARAGE_CODE_A[CLEMSA_CODEGEN_DEFAULT_CODE_SIZE];
extern const uint8_t PARENTS_GARAGE_CODE_B[CLEMSA_CODEGEN_DEFAULT_CODE_SIZE];

extern const uint8_t HOME_2_GARAGE_EXIT_CODE[CLEMSA_CODEGEN_DEFAULT_CODE_SIZE];
extern const uint8_t HOME_2_GARAGE_ENTER_CODE[CLEMSA_CODEGEN_DEFAULT_CODE_SIZE];

#endif
