#ifndef PRIVATE_H
#define PRIVATE_H
#include <stdbool.h>
#include "clemsacode.h"

extern const bool HOME_GARAGE_EXIT_CODE[CLEMSA_CODEGEN_DEFAULT_CODE_SIZE];
extern const bool HOME_GARAGE_ENTER_CODE[CLEMSA_CODEGEN_DEFAULT_CODE_SIZE];
extern const bool PARENTS_GARAGE_ENTER_CODE[CLEMSA_CODEGEN_DEFAULT_CODE_SIZE];
extern const bool PARENTS_GARAGE_EXIT_CODE[CLEMSA_CODEGEN_DEFAULT_CODE_SIZE];

#endif
